### ISSUE TITLE
Do i run the instance double and how can kill one?

### ISSUE THREAD

**Issue by diemen112** [freqtrade/technical#149]
Hello everyone,

I changed my strategy and since i have this error log.

`2021-02-03 16:20:05,842 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.1', state='STOPPED'
2021-02-03 16:20:29,468 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-02-03 16:20:29,469 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 465, in _network_loop_retry
    if not action_cb():
  File "/root/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 420, in polling_action_cb
    allowed_updates=allowed_updates,
  File "<decorator-gen-31>", line 2, in get_updates
  File "/root/.local/lib/python3.7/site-packages/telegram/bot.py", line 135, in decorator
    result = func(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/telegram/bot.py", line 2639, in get_updates
    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs
  File "/root/.local/lib/python3.7/site-packages/telegram/bot.py", line 245, in _post
    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)
  File "/root/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 354, in post
    **urlopen_kwargs,
  File "/root/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 276, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running`

when i do `docker-compose ps` i get this 

![Schermafbeelding 2021-02-03 om 17 40 11](https://user-images.githubusercontent.com/47255128/106779039-de677c80-6646-11eb-8cd6-9deecea78243.png)

do i have to kill the proces after i backtest something?
this is my first time using docker so i don't know much about it.

**Comment by xmatthias** [comment]
you'll be using the same telegrambot twice (maybe intentionally, maybe not) - but as you closed it, i assume you found the solution.

You should however stop some of these bots ... for backtesting, we do NOT use `-d` ;)
