### ISSUE TITLE
docker-compose error 

### ISSUE THREAD

**Issue by mrking89** [freqtrade/technical#167]
Hi, I´ve encountered a problem trying to use the technical dependency with docker-compose 

Processing triggers for libc-bin (2.28-10) ...
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 8, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/cmdoptions.py", line 27, in <module>
    from pip._internal.models.target_python import TargetPython
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 922, in get_code
  File "<frozen importlib._bootstrap_external>", line 980, in get_data
OSError: [Errno 5] Input/output error
ERROR: Service 'freqtrade' failed to build : The command '/bin/sh -c apt-get update     && apt-get -y install git     && apt-get clean     && pip install git+https://github.com/freqtrade/technical' returned a non-zero code: 1

**Comment by xmatthias** [comment]
the "input/output error" suggests that your host system ran out of disk, which will disallow docker to store more changes.

There's other possibilities i think - but the disk one is the most common problem.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
