### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by straj-granicy** [freqtrade/technical#252]
Hi
While running backtesting today I have the following error

2022-02-16 21:07:03,214 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/root/freqtrade/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 672, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 627, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 833, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 833, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
AttributeError: 'NoneType' object has no attribute 'copy'

Please advise what could it be?
I previously ran the strategy few days ago, everything was fine.

**Comment by xmatthias** [comment]
Based on the error it seems like your strategy might not be returning the dataframe from one of the functions.

**Comment by straj-granicy** [comment]
@xmatthias 
True. Thank you.
