### ISSUE TITLE
Could not load markets, therefore cannot start. Please investigate the above error for more details.

### ISSUE THREAD

**Issue by straj-granicy** [freqtrade/technical#258]
Hi.
I previously ran freqtrade in dry run mode, everything worked.
Now I've changed some setting in Binance (entered my IP address, as it was recommended).
Now I have this error

```
2022-03-28 19:58:42,760 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 617, in fetch
    response.raise_for_status()
  File "/root/freqtrade/.env/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1648497522450&recvWindow=5000&signature=cadc3fa2f57c71152395c4bd9f09f9683da5aefe6f2a301c300d0c932670169a

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/exchange/exchange.py", line 339, in _load_markets
    self._markets = self._api.load_markets()
  File "/root/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1424, in load_markets
    currencies = self.fetch_currencies()
  File "/root/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 994, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/root/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 4552, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/root/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 506, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 633, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 4532, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/root/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 524, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
2022-03-28 19:58:42,768 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2022-03-28 19:58:42,768 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/root/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/root/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 65, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/root/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/root/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/root/freqtrade/freqtrade/exchange/exchange.py", line 153, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/root/freqtrade/freqtrade/exchange/exchange.py", line 370, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
```
Please advise whether it's connected with IP address change? Or it's another reason for that?
Thanks for help.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

> `ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}`

It's pretty clear - your api key is invalid.
this can be a typo, leading/trailing space, or a wrong IP restriction on the API key.
Which of these is up to you to figure out - as the exchange is not providing more details.

**Comment by straj-granicy** [comment]
@xmatthias,
It was my mistake.
Close this topic.
