### ISSUE TITLE
How to plot segtrends or gentrends using freqtrade plot-dataframe ?

### ISSUE THREAD

**Issue by SamirFarhat** [freqtrade/technical#317]
I'm trying to use the trendline library from [technical](https://github.com/freqtrade/technical/blob/main/technical/trendline.py).
I don't know if the output is supported with the plot feature as i don't know if the ouput dataframe is of the same dimension.

I have added the following line to  **populate_indicator**s def
dataframe['segtrends'] = trendline.segtrends(dataframe,"close",3.0,False) 

I receive the error when using freqqtrade plot-dataframe 

```
2023-02-26 09:22:27,498 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/sam/freqtrade/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/home/sam/freqtrade/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "/home/sam/freqtrade/freqtrade/freqtrade/plot/plotting.py", line 647, in load_and_plot_trades
    df_analyzed = strategy.analyze_ticker(data, {'pair': pair})
  File "/home/sam/freqtrade/freqtrade/freqtrade/strategy/interface.py", line 831, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/home/sam/freqtrade/freqtrade/freqtrade/strategy/interface.py", line 1339, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/sam/repos/trading/freq/strategies/tests/trendlinesv1.py", line 286, in populate_indicators
    dataframe['segtrends'] = trendline.segtrends(dataframe,"close",3.0,False)
  File "/home/sam/freqtrade/freqtrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 3970, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/sam/freqtrade/freqtrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 4125, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column segtrends

```

**Comment by xmatthias** [comment]
based on the code - the return value is a dataframe with the following 3 columns: `["Data", "Max Line", "Min Line"]`).

You therefore need to assign each of these columns individually to the original dataframe (in multiple steps) - using a temporary variable to store the actual result.

Once it's in the main dataframe (as series, not as nested dataframe) - there should be no problems to plot it using the regular plot configuration.
